# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: akhramut <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/01/23 19:46:24 by akhramut          #+#    #+#              #
#    Updated: 2017/01/29 18:18:37 by akhramut         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = rush-2

all: $(NAME)

$(NAME):
	gcc -Wall -Wextra -Werror -o $(NAME) *.c

clean:
	/bin/rm -f *.o

fclean: clean
	/bin/rm -f $(NAME)
